stages:
  - build
  - test
  - deploy

variables:
  NODE_VERSION: "14"
  DOCKER_IMAGE_NAME: "arosajedash"

before_script:
  - cd ArosajeDash
  - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .next/

test:
  stage: test
  script:
    - npm test

docker_build:
  stage: deploy
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
  only:
    - master

docker_push:
  stage: deploy
  script:
    - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USERNAME --password-stdin
    - docker push $DOCKER_IMAGE_NAME
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker pull $DOCKER_IMAGE_NAME
    - docker run -d -p 3000:3000 $DOCKER_IMAGE_NAME
  only:
    - master
