name: React Native Expo CI

# Jobs
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 12

    - name: Install Dependencies
      run: npm install

    - name: Lint
      run: npx eslint . --fix

    # Exemple d'étape de test - à configurer selon vos tests
    - name: Run Tests
      run: npm test

    # Build Expo (iOS et Android) - Utiliser avec précaution, car cela peut consommer des ressources
    - name: Build Android
      run: expo build:android
      env:
        EXPO_CLI_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
        EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}

    - name: Build iOS
      run: expo build:ios
      env:
        EXPO_CLI_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
        EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}

    # Publication Expo
    - name: Publish to Expo
      run: expo publish
      env:
        EXPO_CLI_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
        EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
